export const theme = {
    fontSize: {
        bannerLarge: "64px",
        bannerMedium: "48px",
        svgLarge: "40px",
        h2: "32px",
        svg: "28px",
        btn: "24px",
        h3: "22px",
        h4: "18px",
        bodyLarge: "16px",
        body: "14px",
        bodySmall: "12px",
    },
    fontWeight: {
        xxl: "900",
        xl: "700",
        l: "500",
        m: "400",
        s: "300",
        xs: "100",
    },
    color: {
        lightGrey: "#aaa",
        grey: "#555",
        black: "#333",
        white: "#fff",
        light_primary: "#eee",
        alert: "#e83927",
        success: "#40a85f",
        brown: "#918481",
        yellow: "#d4ad54",
    },
}